; OPCODE_TEST 6 modifier pass: one pixel per table slot (x = slot). Table (s[0:1]): [0..3] V# of the slots
; {op, a, b, c} (op bits 7..0; 0xff: a heading), [4..7] V# of the results ([11] bytes a slot: lo, hi a float mode),
; [8] this pass's byte offset in a result (mode * 8), [9] slot count, [10] marker. Runs the instructions of
; tools/gen_optest6.py on the slot's operands, keeps the slot's; FLOAT_MODE from PGM_RSRC1. Slot 0 stores the
; marker at [slot count * [11] + mode * 4]. [12] instruction limit: op k runs only if k < [12] (main.c's
; start-up bisection). Generated by tools/gen_optest6.py.
s_load_dwordx8 s[4:11], s[0:1], 0x0
s_load_dwordx4 s[12:15], s[0:1], 0x8
s_load_dword s22, s[0:1], 0xc
s_waitcnt lgkmcnt(0)
v_cvt_u32_f32 v4, v2
v_cmp_gt_u32 vcc, s13, v4
s_and_saveexec_b64 s[16:17], vcc
s_cbranch_execz mod_done
v_lshlrev_b32 v5, 4, v4
buffer_load_dwordx4 v[8:11], v5, s[4:7], 0 offen
s_waitcnt vmcnt(0)
v_and_b32 v8, 0xff, v8
v_mov_b32 v12, 0
v_mov_b32 v13, 0
; op 0: V_ADD_F32
s_cmp_le_u32 s22, 0
s_cbranch_scc1 op0_skip
v_add_f32_e64 v14, v9, v10
v_cmp_eq_u32 vcc, 0, v8
v_cndmask_b32 v12, v12, v14, vcc
op0_skip:
; op 1: V_ADD_F32 mul:2
s_cmp_le_u32 s22, 1
s_cbranch_scc1 op1_skip
v_add_f32_e64 v14, v9, v10 mul:2
v_cmp_eq_u32 vcc, 1, v8
v_cndmask_b32 v12, v12, v14, vcc
op1_skip:
; op 2: V_ADD_F32 mul:4
s_cmp_le_u32 s22, 2
s_cbranch_scc1 op2_skip
v_add_f32_e64 v14, v9, v10 mul:4
v_cmp_eq_u32 vcc, 2, v8
v_cndmask_b32 v12, v12, v14, vcc
op2_skip:
; op 3: V_ADD_F32 div:2
s_cmp_le_u32 s22, 3
s_cbranch_scc1 op3_skip
v_add_f32_e64 v14, v9, v10 div:2
v_cmp_eq_u32 vcc, 3, v8
v_cndmask_b32 v12, v12, v14, vcc
op3_skip:
; op 4: V_MUL_F32 mul:2
s_cmp_le_u32 s22, 4
s_cbranch_scc1 op4_skip
v_mul_f32_e64 v14, v9, v10 mul:2
v_cmp_eq_u32 vcc, 4, v8
v_cndmask_b32 v12, v12, v14, vcc
op4_skip:
; op 5: V_MAX_F32 mul:2
s_cmp_le_u32 s22, 5
s_cbranch_scc1 op5_skip
v_max_f32_e64 v14, v9, v10 mul:2
v_cmp_eq_u32 vcc, 5, v8
v_cndmask_b32 v12, v12, v14, vcc
op5_skip:
; op 6: V_MIN_F32 div:2
s_cmp_le_u32 s22, 6
s_cbranch_scc1 op6_skip
v_min_f32_e64 v14, v9, v10 div:2
v_cmp_eq_u32 vcc, 6, v8
v_cndmask_b32 v12, v12, v14, vcc
op6_skip:
; op 7: V_MUL_LEGACY_F32 mul:2
s_cmp_le_u32 s22, 7
s_cbranch_scc1 op7_skip
v_mul_legacy_f32_e64 v14, v9, v10 mul:2
v_cmp_eq_u32 vcc, 7, v8
v_cndmask_b32 v12, v12, v14, vcc
op7_skip:
; op 8: V_MAD_F32 mul:2
s_cmp_le_u32 s22, 8
s_cbranch_scc1 op8_skip
v_mad_f32 v14, v9, v10, v11 mul:2
v_cmp_eq_u32 vcc, 8, v8
v_cndmask_b32 v12, v12, v14, vcc
op8_skip:
; op 9: V_FMA_F32 div:2
s_cmp_le_u32 s22, 9
s_cbranch_scc1 op9_skip
v_fma_f32 v14, v9, v10, v11 div:2
v_cmp_eq_u32 vcc, 9, v8
v_cndmask_b32 v12, v12, v14, vcc
op9_skip:
; op 10: V_RCP_F32 mul:2
s_cmp_le_u32 s22, 10
s_cbranch_scc1 op10_skip
v_rcp_f32_e64 v14, v9 mul:2
v_cmp_eq_u32 vcc, 10, v8
v_cndmask_b32 v12, v12, v14, vcc
op10_skip:
; op 11: V_SQRT_F32 div:2
s_cmp_le_u32 s22, 11
s_cbranch_scc1 op11_skip
v_sqrt_f32_e64 v14, v9 div:2
v_cmp_eq_u32 vcc, 11, v8
v_cndmask_b32 v12, v12, v14, vcc
op11_skip:
; op 12: V_FRACT_F32 mul:4
s_cmp_le_u32 s22, 12
s_cbranch_scc1 op12_skip
v_fract_f32_e64 v14, v9 mul:4
v_cmp_eq_u32 vcc, 12, v8
v_cndmask_b32 v12, v12, v14, vcc
op12_skip:
; op 13: V_CVT_F32_U32 mul:4
s_cmp_le_u32 s22, 13
s_cbranch_scc1 op13_skip
v_cvt_f32_u32_e64 v14, v9 mul:4
v_cmp_eq_u32 vcc, 13, v8
v_cndmask_b32 v12, v12, v14, vcc
op13_skip:
; op 14: V_CVT_F32_F16 mul:2
s_cmp_le_u32 s22, 14
s_cbranch_scc1 op14_skip
v_cvt_f32_f16_e64 v14, v9 mul:2
v_cmp_eq_u32 vcc, 14, v8
v_cndmask_b32 v12, v12, v14, vcc
op14_skip:
; op 15: V_CVT_F32_F64 div:2
s_cmp_le_u32 s22, 15
s_cbranch_scc1 op15_skip
v_cvt_f32_f64_e64 v14, v[9:10] div:2
v_cmp_eq_u32 vcc, 15, v8
v_cndmask_b32 v12, v12, v14, vcc
op15_skip:
; op 16: V_MUL_F32 clamp mul:2
s_cmp_le_u32 s22, 16
s_cbranch_scc1 op16_skip
v_mul_f32_e64 v14, v9, v10 clamp mul:2
v_cmp_eq_u32 vcc, 16, v8
v_cndmask_b32 v12, v12, v14, vcc
op16_skip:
; op 17: V_ADD_F32 clamp div:2
s_cmp_le_u32 s22, 17
s_cbranch_scc1 op17_skip
v_add_f32_e64 v14, v9, v10 clamp div:2
v_cmp_eq_u32 vcc, 17, v8
v_cndmask_b32 v12, v12, v14, vcc
op17_skip:
; op 18: V_MAD_F32 clamp
s_cmp_le_u32 s22, 18
s_cbranch_scc1 op18_skip
v_mad_f32 v14, v9, v10, v11 clamp
v_cmp_eq_u32 vcc, 18, v8
v_cndmask_b32 v12, v12, v14, vcc
op18_skip:
; op 19: V_ADD_F64 (+1.0) mul:2
s_cmp_le_u32 s22, 19
s_cbranch_scc1 op19_skip
v_add_f64 v[14:15], v[9:10], 1.0 mul:2
v_cmp_eq_u32 vcc, 19, v8
v_cndmask_b32 v12, v12, v14, vcc
v_cndmask_b32 v13, v13, v15, vcc
op19_skip:
; op 20: V_MUL_F64 (*0.5) div:2
s_cmp_le_u32 s22, 20
s_cbranch_scc1 op20_skip
v_mul_f64 v[14:15], v[9:10], 0.5 div:2
v_cmp_eq_u32 vcc, 20, v8
v_cndmask_b32 v12, v12, v14, vcc
v_cndmask_b32 v13, v13, v15, vcc
op20_skip:
; op 21: V_FMA_F64 (*1+0) mul:4
s_cmp_le_u32 s22, 21
s_cbranch_scc1 op21_skip
v_fma_f64 v[14:15], v[9:10], 1.0, 0 mul:4
v_cmp_eq_u32 vcc, 21, v8
v_cndmask_b32 v12, v12, v14, vcc
v_cndmask_b32 v13, v13, v15, vcc
op21_skip:
; op 22: V_CVT_F16_F32 mul:2
s_cmp_le_u32 s22, 22
s_cbranch_scc1 op22_skip
v_mov_b32 v14, 0xdead0000
v_cvt_f16_f32_e64 v14, v9 mul:2
v_cmp_eq_u32 vcc, 22, v8
v_cndmask_b32 v12, v12, v14, vcc
op22_skip:
; op 23: V_CVT_PKRTZ_F16_F32 mul:2
s_cmp_le_u32 s22, 23
s_cbranch_scc1 op23_skip
v_cvt_pkrtz_f16_f32_e64 v14, v9, v10 mul:2
v_cmp_eq_u32 vcc, 23, v8
v_cndmask_b32 v12, v12, v14, vcc
op23_skip:
; op 24: V_CVT_I32_F32 mul:2
s_cmp_le_u32 s22, 24
s_cbranch_scc1 op24_skip
v_cvt_i32_f32_e64 v14, v9 mul:2
v_cmp_eq_u32 vcc, 24, v8
v_cndmask_b32 v12, v12, v14, vcc
op24_skip:
; op 25: V_CVT_U32_F32 div:2
s_cmp_le_u32 s22, 25
s_cbranch_scc1 op25_skip
v_cvt_u32_f32_e64 v14, v9 div:2
v_cmp_eq_u32 vcc, 25, v8
v_cndmask_b32 v12, v12, v14, vcc
op25_skip:
; op 26: V_ADD_F32 (-src0)
s_cmp_le_u32 s22, 26
s_cbranch_scc1 op26_skip
v_add_f32_e64 v14, -v9, v10
v_cmp_eq_u32 vcc, 26, v8
v_cndmask_b32 v12, v12, v14, vcc
op26_skip:
; op 27: V_MAX_F32 (|src0|)
s_cmp_le_u32 s22, 27
s_cbranch_scc1 op27_skip
v_max_f32_e64 v14, |v9|, v10
v_cmp_eq_u32 vcc, 27, v8
v_cndmask_b32 v12, v12, v14, vcc
op27_skip:
; op 28: V_MUL_F32 (-|src0|)
s_cmp_le_u32 s22, 28
s_cbranch_scc1 op28_skip
v_mul_f32_e64 v14, -|v9|, v10
v_cmp_eq_u32 vcc, 28, v8
v_cndmask_b32 v12, v12, v14, vcc
op28_skip:
; op 29: V_CVT_F32_F16 (-src)
s_cmp_le_u32 s22, 29
s_cbranch_scc1 op29_skip
v_cvt_f32_f16_e64 v14, -v9
v_cmp_eq_u32 vcc, 29, v8
v_cndmask_b32 v12, v12, v14, vcc
op29_skip:
; op 30: V_CVT_F32_F64 (|src|)
s_cmp_le_u32 s22, 30
s_cbranch_scc1 op30_skip
v_cvt_f32_f64_e64 v14, |v[9:10]|
v_cmp_eq_u32 vcc, 30, v8
v_cndmask_b32 v12, v12, v14, vcc
op30_skip:
v_mul_u32_u24 v6, s15, v4
v_add_i32 v6, vcc, s12, v6
buffer_store_dwordx2 v[12:13], v6, s[8:11], 0 offen
v_cmp_eq_u32 vcc, 0, v4
s_and_saveexec_b64 s[18:19], vcc
s_cbranch_execz mod_nomark
s_mul_i32 s20, s13, s15
s_lshr_b32 s21, s12, 1
s_add_u32 s20, s20, s21
v_mov_b32 v7, s20
v_mov_b32 v16, s14
buffer_store_dword v16, v7, s[8:11], 0 offen
mod_nomark:
s_mov_b64 exec, s[18:19]
mod_done:
s_mov_b64 exec, s[16:17]
v_mov_b32 v0, 0
exp mrt0 v0, v0, v0, v0 done vm
s_endpgm
