#pragma once
/* Every GCN shader binary. The headers are generated from the .s sources by the header tool
   (hash, PGM_RSRC1 in each header's comment); ps_blue, ps_shadow, ps_shadow_clear, vs_shader and
   vs_shadow have no .s: hand-assembled. */
/* GPU shader binaries (GCN2 / Sea Islands). The .s files next to the post,
   ps_stars and ps_dark shaders are their llvm-mc sources (see README.txt). */
#include "ps_blue.h"
#include "ps_dark.h"
#include "ps_floor.h"
#include "ps_model.h"
#include "ps_post_blur.h"
#include "ps_post_comp.h"
#include "ps_post_down.h"
#include "ps_post_final.h"
#include "ps_ui.h"
#include "ps_clock.h"
#include "ps_clock_light.h"
#include "ps_resolve.h"
#include "ps_shader.h"
#include "ps_shadow.h"
#include "ps_shadow_clear.h"
#include "ps_stars.h"
#include "vs_shader.h"
#include "vs_shadow.h"
#include "vs_model.h"
#include "vs_model_shadow.h"
#include "ps_cvt_0.h"
#include "ps_cvt_1.h"
#include "ps_cvt_2.h"
#include "ps_cvt_3.h"
#include "ps_cvt_4.h"
#include "ps_mod_0.h"
#include "ps_mod_1.h"
#include "ps_mod_2.h"
#include "ps_mod_3.h"
#include "ps_mod_4.h"
#include "ps_mod_5.h"
#include "ps_mod_6.h"
#include "ps_mod_7.h"
#include "ps_mod_8.h"
#include "ps_mod_9.h"
#include "ps_mod_10.h"
#include "ps_mod_11.h"
#include "ps_mod_12.h"
#include "ps_mod_13.h"
#include "ps_mod_14.h"
#include "ps_mod_15.h"
#include "ps_mod_16.h"
#include "ps_mod_17.h"
#include "ps_mod_18.h"
#include "ps_mod_19.h"
