#!/usr/bin/env python3
"""shaders/ps_cvt.s and shaders/ps_cvt_full.s - the OPCODE_TEST 5 conversion pass. One pixel per table slot runs
every V_CVT_* on the slot's operands and keeps the slot's op (src/optest5.h numbering). ps_cvt.s leaves out
V_CVT_U32_F64 and V_CVT_PKACCUM_U8_F32 (no shadPS4 translator: its assert stops the shader); ps_cvt_full.s
(OPT5_FULL, PS4 only) has all of them. V_CVT_OFF_F32_I4 takes immediate operands only (shadPS4 asserts on a
register): one instruction per value of its rows in src/optest5.h, kept for op 18 with that a.
python3 tools/gen_ps_cvt.py"""
import os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# (op index in src/optest5.h, instructions writing v14 / v[14:15], 64-bit result)
OPS = [(0, "v_cvt_i32_f32 v14, v9", 0), (1, "v_cvt_u32_f32 v14, v9", 0), (2, "v_cvt_flr_i32_f32 v14, v9", 0),
       (3, "v_cvt_rpi_i32_f32 v14, v9", 0), (4, "v_cvt_i32_f64 v14, v[9:10]", 0), (5, "v_cvt_u32_f64 v14, v[9:10]", 0),
       (6, "v_cvt_f32_i32 v14, v9", 0), (7, "v_cvt_f32_u32 v14, v9", 0), (8, "v_cvt_f64_i32 v[14:15], v9", 1),
       (9, "v_cvt_f64_u32 v[14:15], v9", 1), (10, "v_cvt_f64_f32 v[14:15], v9", 1), (11, "v_cvt_f32_f64 v14, v[9:10]", 0),
       (12, "v_mov_b32 v14, 0xdead0000\nv_cvt_f16_f32 v14, v9", 0), (13, "v_cvt_f32_f16 v14, v9", 0),
       (14, "v_cvt_f32_ubyte0 v14, v9", 0), (15, "v_cvt_f32_ubyte1 v14, v9", 0), (16, "v_cvt_f32_ubyte2 v14, v9", 0),
       (17, "v_cvt_f32_ubyte3 v14, v9", 0), (18, "v_cvt_off_f32_i4 v14, v9", 0), (19, "v_cvt_pkrtz_f16_f32 v14, v9, v10", 0),
       (20, "v_cvt_pknorm_i16_f32 v14, v9, v10", 0), (21, "v_cvt_pknorm_u16_f32 v14, v9, v10", 0),
       (22, "v_cvt_pk_u16_u32 v14, v9, v10", 0), (23, "v_cvt_pk_i16_i32 v14, v9, v10", 0),
       (24, "v_mov_b32 v14, v11\nv_cvt_pkaccum_u8_f32 v14, v9, v10", 0), (25, "v_cvt_pk_u8_f32 v14, v9, v10, v11", 0),
       # VOP3 input / output modifiers
       (26, "v_cvt_i32_f32_e64 v14, -v9", 0), (27, "v_cvt_flr_i32_f32_e64 v14, |v9|", 0),
       (28, "v_cvt_f32_i32_e64 v14, v9 clamp", 0), (29, "v_cvt_f32_u32_e64 v14, v9 mul:2", 0),
       (30, "v_cvt_f32_u32_e64 v14, v9 div:2", 0), (31, "v_mov_b32 v14, 0xdead0000\nv_cvt_f16_f32_e64 v14, -v9", 0),
       (32, "v_cvt_f64_f32_e64 v[14:15], |v9|", 1), (33, "v_cvt_pkrtz_f16_f32_e64 v14, v9, -v10", 0),
       (34, "v_cvt_f32_f64_e64 v14, -v[9:10]", 0)]
FULL_ONLY = (5, 24)
OFF_I4 = 18
def off_values():
    h = open(os.path.join(ROOT, "src", "optest5.h")).read()
    vals = [int(a, 16) for op, a in re.findall(r"\{(\d+), 0x([0-9A-F]+)u,", h) if int(op) == OFF_I4]
    return sorted(set(vals), key=vals.index)
def source(full):
    L = ["; OPCODE_TEST 5 conversion pass%s: one pixel per table slot (a 384 x 1 target, x = slot). Table (s[0:1]):" % (" (all V_CVT_*, PS4 only)" if full else ""),
         "; [0..3] V# of the slots {op, a, b, c} (op bits 7..0; 0xff: a heading), [4..7] V# of the results (48 bytes a",
         "; slot: lo, hi for float modes A..E), [8] this pass's byte offset in a result (mode * 8), [9] slot count,",
         "; [10] marker. Runs the V_CVT_* on the",
         "; slot's operands and keeps the slot's op (a, b = an f64 source; c = PK_U8's S2, PKACCUM's destination);",
         "; FLOAT_MODE from PGM_RSRC1 (A 0x00, B 0xC0, C 0x10, D 0x20, E 0x30). Slot 0 stores the marker at [slot count * 48 +"
         " mode * 4]."
         + ("" if full else " Without V_CVT_U32_F64 and V_CVT_PKACCUM_U8_F32 (no shadPS4 translator)."),
         "; Generated by tools/gen_ps_cvt.py.",
         "s_load_dwordx8 s[4:11], s[0:1], 0x0", "s_load_dwordx4 s[12:15], s[0:1], 0x8", "s_waitcnt lgkmcnt(0)",
         "v_cvt_u32_f32 v4, v2", "v_cmp_gt_u32 vcc, s13, v4", "s_and_saveexec_b64 s[16:17], vcc", "s_cbranch_execz cvt_done",
         "v_lshlrev_b32 v5, 4, v4", "buffer_load_dwordx4 v[8:11], v5, s[4:7], 0 offen", "s_waitcnt vmcnt(0)",
         "v_and_b32 v8, 0xff, v8", "v_mov_b32 v12, 0", "v_mov_b32 v13, 0"]
    for k, ins, wide in OPS:
        if k in FULL_ONLY and not full:
            continue
        if k == OFF_I4: # immediate operands: vcc = op 18 and a == the value
            L += ["; op %d: V_CVT_OFF_F32_I4 on immediates" % k, "v_cmp_eq_u32_e64 s[22:23], %d, v8" % k]
            for v in off_values():
                imm = str(v - (1 << 32)) if v >= 0xFFFFFFF0 else ("%d" % v if v <= 64 else "0x%x" % v)
                L += ["v_cvt_off_f32_i4 v14, %s" % imm, "v_cmp_eq_u32 vcc, 0x%x, v9" % v, "s_and_b64 vcc, vcc, s[22:23]",
                      "v_cndmask_b32 v12, v12, v14, vcc"]
            continue
        L.append("; op %d" % k)
        L += ins.split("\n")
        L += ["v_cmp_eq_u32 vcc, %d, v8" % k, "v_cndmask_b32 v12, v12, v14, vcc"]
        if wide:
            L.append("v_cndmask_b32 v13, v13, v15, vcc")
    L += ["v_lshlrev_b32 v6, 1, v5", "v_add_i32 v6, vcc, v6, v5", "v_add_i32 v6, vcc, s12, v6",
          "buffer_store_dwordx2 v[12:13], v6, s[8:11], 0 offen",
          "v_cmp_eq_u32 vcc, 0, v4", "s_and_saveexec_b64 s[18:19], vcc", "s_cbranch_execz cvt_nomark",
          "s_lshl_b32 s20, s13, 5", "s_lshl_b32 s21, s13, 4", "s_add_u32 s20, s20, s21", "s_lshr_b32 s21, s12, 1",
          "s_add_u32 s20, s20, s21", "v_mov_b32 v7, s20", "v_mov_b32 v16, s14",
          "buffer_store_dword v16, v7, s[8:11], 0 offen", "cvt_nomark:", "s_mov_b64 exec, s[18:19]", "cvt_done:",
          "s_mov_b64 exec, s[16:17]", "v_mov_b32 v0, 0", "exp mrt0 v0, v0, v0, v0 done vm", "s_endpgm"]
    return "\n".join(L) + "\n"
for name, full in (("ps_cvt.s", 0), ("ps_cvt_full.s", 1)):
    open(os.path.join(ROOT, "shaders", name), "w").write(source(full))
    print("shaders/%s" % name)
